
stages:
  - test
  - build
  
run_tests:
  stage: test
  image: python:3.9-alpine
  script:
    - echo "some tesst"

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/crud-vuejs-django_backend:1.2 ./subcription-api
    - docker push gerrome/crud-vuejs-django_backend:1.2

