
stages:
  - test
  - build
  - build-docker

test_vuejs:
  stage: test
  image: node:16.13.1-alpine
  script:
    - yarn test
    - yarn lint

build_vuejs:
  stage: build
  image: node:16.13.1-alpine
  script:
    - cd subscription-app
    - npm install
    - npm run build


build_django:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/crud-vuejs-django_backend:1.2 ./subscription-api
    - docker push gerrome/crud-vuejs-django_backend:1.2

build_vue-nginx:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/crud-vuejs-django_nginx:1.2 ./subscription-app
    - docker push gerrome/crud-vuejs-django_nginx:1.2
