version: "3.8"

services:
  api:
    #build:
    #  context: ./subscription-apip
    image: gerrome/django-vuejs_api:1
    volumes:
      - .:/app3
      - static_volume:/app3/staticfiles
      - media_volume:/app3/mediafiles   
    expose:
      - 8000

  app:
    image: gerrome/django-vuejs_app:1
    #build:
    #  context: ./subscription-app
    ports:
      - "80:80"
    volumes:
      - static_volume:/app3/staticfiles
      - media_volume:/app3/mediafiles    
    depends_on:
      - backend


volumes:
  static_volume:
  media_volume:



