version: "3.8"

services:
  backend:
    #build:
    #  context: ./subscription-apip
    image: gerrome/crud-vuejs-django_backend:1.2
    volumes:
      - .:/app3
      - static_volume:/app3/staticfiles
      - media_volume:/app3/mediafiles   
    expose:
      - 8000

  nginx:
    image: gerrome/crud-vuejs-django_nginx:1.2
    #build:
    #  context: ./subscription-app
    ports:
      - "80:80"
    volumes:
      - static_volume:/app3/staticfiles
      - media_volume:/app3/mediafiles    
    depends_on:
      - backend


volumes:
  static_volume:
  media_volume:



